### PR TITLE
Implement Checkstyle

### PR DESCRIPTION
**Pull request by pietelite**

### CODE REVIEW

**Comment by Geph** [comment]
@jackah2 or @pietelite appreciate if you could make sure this is okay. Mostly just trying to push the Quests Repo alteration, but also some of the checkstyle updates. It's griping because I didn't do all of the checkstyle requirements, I think, but please make sure that's the case.

**Comment by pietelite** [comment]
> It's griping because I didn't do all of the checkstyle requirements, I think, but please make sure that's the case.

Yeah, that's the case

**Comment by jackah2** [comment]
I went through and fixed all the Checkstyle errors it was reporting.

**Review by Geph — APPROVED** [review]
Looked over all changes, didn't catch anything that wasn't appropriate or needed.

**Pull request merged**
